export const ADMISSION_REPOSITORY = Symbol('ADMISSION_REPOSITORY');
export const ADMISSION_EVENT_REPOSITORY = Symbol('ADMISSION_EVENT_REPOSITORY');
export const QR_TOKEN_VERIFIER = Symbol('QR_TOKEN_VERIFIER');