export const PAYMENT_REPOSITORY = Symbol('PAYMENT_REPOSITORY');
export const LEDGER_REPOSITORY = Symbol('LEDGER_REPOSITORY');
export const PAYMENT_INTENT_REPOSITORY = Symbol('PAYMENT_INTENT_REPOSITORY');
export const PAYMENT_INTENT_AUDIT_LOG_REPOSITORY = Symbol(
	'PAYMENT_INTENT_AUDIT_LOG_REPOSITORY',
);
export const PROVIDER_WEBHOOK_EVENT_REPOSITORY = Symbol(
	'PROVIDER_WEBHOOK_EVENT_REPOSITORY',
);
export const PAYSTACK_PROVIDER = Symbol('PAYSTACK_PROVIDER');
export const MOMO_PROVIDER = Symbol('MOMO_PROVIDER');