import { AppPermission } from '../common/constants/permissions';
import { AppRole } from '../common/constants/roles';

export const ROLE_PERMISSIONS: Record<AppRole, AppPermission[]> = {
  [AppRole.CUSTOMER]: [
    AppPermission.AUTHENTICATED,
    AppPermission.CUSTOMER_ACCESS,
    AppPermission.SESSION_REVOKE_OWN,
    AppPermission.USER_READ_SELF,
    AppPermission.ORGANIZER_CREATE,
    AppPermission.ORGANIZER_READ_OWN,
    AppPermission.ORGANIZER_UPDATE_OWN,
    AppPermission.ORGANIZER_SUBMIT_OWN,
    AppPermission.EVENT_CREATE_OWN,
    AppPermission.EVENT_READ_OWN,
    AppPermission.EVENT_UPDATE_OWN,
    AppPermission.EVENT_PUBLISH_OWN,
    AppPermission.EVENT_CANCEL_OWN,
    AppPermission.TABLE_READ_PUBLIC,
    AppPermission.TABLE_HOLD_OWN,
    AppPermission.TABLE_READ_OWN_RESERVATION,
    AppPermission.PAYMENT_INITIATE_OWN,
    AppPermission.PAYMENT_READ_OWN,
    AppPermission.TICKET_READ_OWN,
  ],
  [AppRole.ORGANIZER]: [
    AppPermission.AUTHENTICATED,
    AppPermission.ORGANIZER_ACCESS,
    AppPermission.SESSION_REVOKE_OWN,
    AppPermission.USER_READ_SELF,
    AppPermission.ORGANIZER_CREATE,
    AppPermission.ORGANIZER_READ_OWN,
    AppPermission.ORGANIZER_UPDATE_OWN,
    AppPermission.ORGANIZER_SUBMIT_OWN,
    AppPermission.EVENT_CREATE_OWN,
    AppPermission.EVENT_READ_OWN,
    AppPermission.EVENT_UPDATE_OWN,
    AppPermission.EVENT_PUBLISH_OWN,
    AppPermission.EVENT_CANCEL_OWN,
    AppPermission.TABLE_MANAGE_ORGANIZER,
    AppPermission.TABLE_READ_ORGANIZER,
    AppPermission.PAYMENT_INITIATE_OWN,
    AppPermission.PAYMENT_READ_OWN,
    AppPermission.TICKET_READ_OWN,
    AppPermission.ADMISSION_SCAN_EVENT,
  ],
  [AppRole.GATE_STAFF]: [
    AppPermission.AUTHENTICATED,
    AppPermission.GATE_STAFF_ACCESS,
  ],
  [AppRole.ADMIN]: [
    AppPermission.AUTHENTICATED,
    AppPermission.ADMIN_ACCESS,
    AppPermission.ADMIN_SUPPORT_READ_USERS,
    AppPermission.ADMIN_SUPPORT_READ_ORGANIZERS,
    AppPermission.ADMIN_SUPPORT_READ_EVENTS,
    AppPermission.ADMIN_SUPPORT_READ_PAYMENTS,
    AppPermission.ADMIN_SUPPORT_READ_TICKETS,
    AppPermission.ADMIN_SUPPORT_READ_ADMISSIONS,
    AppPermission.ADMIN_SUPPORT_READ_AUDIT_LOGS,
    AppPermission.SESSION_REVOKE_OWN,
    AppPermission.SESSION_REVOKE_ANY,
    AppPermission.USER_READ_SELF,
    AppPermission.ORGANIZER_CREATE,
    AppPermission.ORGANIZER_READ_OWN,
    AppPermission.ORGANIZER_UPDATE_OWN,
    AppPermission.ORGANIZER_SUBMIT_OWN,
    AppPermission.EVENT_CREATE_OWN,
    AppPermission.EVENT_READ_OWN,
    AppPermission.EVENT_UPDATE_OWN,
    AppPermission.EVENT_PUBLISH_OWN,
    AppPermission.EVENT_CANCEL_OWN,
    AppPermission.TABLE_MANAGE_ORGANIZER,
    AppPermission.TABLE_READ_ORGANIZER,
    AppPermission.TABLE_READ_PUBLIC,
    AppPermission.TABLE_HOLD_OWN,
    AppPermission.TABLE_READ_OWN_RESERVATION,
    AppPermission.PAYMENT_INITIATE_OWN,
    AppPermission.PAYMENT_READ_OWN,
    AppPermission.TICKET_READ_OWN,
  ],
};